apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-agent
  labels:
    app: recruitment-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruitment-agent
  template:
    metadata:
      labels:
        app: recruitment-agent
    spec:
      containers:
      - name: recruitment-agent
        image: recruitment-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: recruitment-agent-config
              key: DATABASE_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: recruitment-agent-config
              key: LOG_LEVEL
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: recruitment-agent-config
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: recruitment-agent-config
              key: SMTP_PORT
        - name: UPLOAD_DIR
          valueFrom:
            configMapKeyRef:
              name: recruitment-agent-config
              key: UPLOAD_DIR
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
