apiVersion: v1
kind: Service
metadata:
  name: recruitment-agent
  labels:
    app: recruitment-agent
spec:
  selector:
    app: recruitment-agent
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
