apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruitment-agent
  template:
    spec:
      containers:
      - name: recruitment-agent
        imagePullPolicy: Never  # For local development
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
        resources:
          limits:
            cpu: "300m"
            memory: "300Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
