apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Production-specific patches
patchesStrategicMerge:
- patch.yaml

# Production-specific configurations
configMapGenerator:
- name: recruitment-agent-config
  behavior: merge
  literals:
  - log_level=info
  - database_url=postgresql://postgres:${DB_PASSWORD}@postgres-prod:5432/recruitment-prod
  
# Production secrets (in a real environment, use sealed secrets or external secret management)
secretGenerator:
- name: recruitment-agent-secrets
  literals:
  - smtp_user=prod-smtp-user
  - smtp_password=${SMTP_PASSWORD}
